name: GitHub Classroom Autograding

on: [push, workflow_dispatch]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    
    # Bỏ qua chạy test nếu người commit là bot của classroom
    # (giống hệt file Python của bạn)
    if: github.actor != 'github-classroom[bot]'
    
    steps:
      # 1. Check out code của sinh viên
      - name: Checkout code
        uses: actions/checkout@v4 # Dùng v4 mới nhất

      # 2. Chạy bộ test
      # Action này sẽ tự động:
      #  - Tìm file .github/classroom/autograding.json
      #  - Chạy lệnh "setup" và "run" trong file đó (tức là 'make all' và 'make run')
      #  - Tìm file results.json do test_runner.cpp tạo ra
      #  - Phân tích file JSON đó và báo cáo điểm chi tiết (vd: 8/10)
      - name: Run autograding
        uses: education/github-classroom-autograding-action@v1
