name: GitHub Classroom Autograding

on: [push, workflow_dispatch]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    
    # Bỏ qua việc chạy test nếu người commit là bot của classroom
    if: github.actor != 'github-classroom[bot]'
    
    steps:
      # 1. Check out code của sinh viên
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Chạy bộ test và đăng kết quả
      - name: Run autograding
        # Đảm bảo dòng này chính xác 100%, bao gồm cả @v1
        uses: education/github-classroom-autograding-action@v1
